version: "3.8"

services:
  xsisapp-api-db:
    restart: always
    container_name: xsisapp-api-db
    image: postgres:13-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: ekosutrisno
      POSTGRES_USER: ekosutrisno
      POSTGRES_DB: db_xsisapp_master
    networks:
      - mynetwork
  xsisapp-api-service:
    container_name: xsisapp-api-service-v1
    image: xsisapp-api-service:0.0.1
    ports:
      - 8090:8090
    environment:
      DATABASE_USERNAME: ekosutrisno
      DATABASE_PASSWORD: ekosutrisno
      DATABASE_URL: jdbc:postgresql://xsisapp-api-db/db_xsisapp_master
    networks:
      - mynetwork
    depends_on:
      - xsisapp-api-db

networks:
  mynetwork:
    external: true
    driver: bridge