version: "3.8"

services:
  employee-api-db:
    restart: always
    container_name: employee-api-db
    image: postgres:13-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: ekosutrisno
      POSTGRES_USER: ekosutrisno
      POSTGRES_DB: db_employee_master
    networks:
      - mynetwork
  employee-api-service:
    container_name: employee-api-service
    image: employee-service:0.0.1
    ports:
      - 8090:8090
    environment:
      DATABASE_USERNAME: ekosutrisno
      DATABASE_PASSWORD: ekosutrisno
      DATABASE_URL: jdbc:postgresql://employee-api-db/db_employee_master
    networks:
      - mynetwork
    depends_on:
      - employee-api-db

networks:
  mynetwork:
    external: true
    driver: bridge