server:
  port: 8090
  servlet:
    context-path: /xsisapp/api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/xsisapp}
    password: ${DATABASE_PASSWORD:admin}
    username: ${DATABASE_USERNAME:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false



